### ISSUE TITLE
Build SUPA with autoconf

### ISSUE THREAD

**Issue by rainoftime** [SVF-tools/SUPA#1]
After moving the files to SVF,
~~~~
cp -r include $SVF_HOME
cp -r lib $SVF_HOME
cp -r tools $SVF_HOME
~~~~
I tried to compile SUPA with autoconf, following the guidance below:
https://github.com/SVF-tools/SVF/wiki/Setup-Guide-(Autoconf)

I changed the `SVF/autoconf/configure.ac` by adding 
~~~~
AC_CONFIG_MAKEFILE(Makefile)
AC_CONFIG_MAKEFILE(lib/Makefile)
AC_CONFIG_MAKEFILE(lib/DDA/Makefile)
AC_CONFIG_MAKEFILE(lib/WPA/Makefile)
AC_CONFIG_MAKEFILE(lib/MemoryModel/Makefile)
AC_CONFIG_MAKEFILE(lib/Util/Makefile)
AC_CONFIG_MAKEFILE(tools/Makefile)
AC_CONFIG_MAKEFILE(tools/WPA/Makefile)
AC_CONFIG_MAKEFILE(tools/DDA/Makefile)
~~~~

DDA library and dvf were compiled successfully. wap and saber can work as usual.  But when running `./dvf`, I got a segment fault, and gdb gave the following trace:

~~~~
(gdb) bt
#0  __strcmp_sse2_unaligned () at ../sysdeps/x86_64/multiarch/strcmp-sse2-unaligned.S:32
#1  0x0000000000a139e6 in llvm::cl::generic_parser_base::findOption(char const*) ()
#2  0x00007fec68118303 in void llvm::cl::parser<PointerAnalysis::PTATY>::addLiteralOption<int>(char const*, int const&, char const*) () from /home/test/SVF/Release+Asserts/bin/../lib/libdvf.so
#3  0x00007fec68116316 in llvm::cl::bits<PointerAnalysis::PTATY, bool, llvm::cl::parser<PointerAnalysis::PTATY> >::bits<llvm::cl::desc, llvm::cl::ValuesClass<int> >(llvm::cl::desc const&, llvm::cl::ValuesClass<int> const&) () from /home/test/SVF/Release+Asserts/bin/../lib/libdvf.so
#4  0x00007fec680fe672 in _GLOBAL__sub_I_DDAPass.cpp ()
   from /home/test/SVF/Release+Asserts/bin/../lib/libdvf.so
#5  0x0000000000e6eb00 in vtable for llvm::cl::OptionValue<bool> ()
#6  0x0000000000e78250 in vtable for llvm::cl::parser<bool> ()
#7  0x000000000156ef40 in ?? ()
#8  0x000000000156f078 in ?? ()
#9  0x000000000156f108 in ?? ()
#10 0x00007fec6812be75 in ?? () from /home/test/SVF/Release+Asserts/bin/../lib/libdvf.so
#11 0x00007fec0000000f in ?? ()
#12 0x00007fec6812be79 in ?? () from /home/test/SVF/Release+Asserts/bin/../lib/libdvf.so
#13 0x00007fec6812bcd1 in ?? () from /home/test/SVF/Release+Asserts/bin/../lib/libdvf.so
#14 0x00007fec00000011 in ?? ()
#15 0x00007fec6812be9f in ?? () from /home/test/SVF/Release+Asserts/bin/../lib/libdvf.so
#16 0x0000000000e6eb00 in vtable for llvm::cl::OptionValue<bool> ()
#17 0x0000000000e78250 in vtable for llvm::cl::parser<bool> ()
#18 0x00007fff3e6fcef0 in ?? ()
~~~~
My LLVM version is 3.6.0.  Would you please give some feedback about this problem? Thank you!

**Comment by yuleisui** [comment]
Autoconf builds in LLVM are replaced by CMake after version 4.0. Since SVF requires LLVM build files, we didn't maintain Autoconf for later LLVM versions other than 4.0.

May I know why not using CMake but Autoconf, any reasons behind?

**Comment by rainoftime** [comment]
One of my project based on LLVM 3.6.0 is using SVF, and it is built with autoconf. I was trying to integrate SUPA to improve the precision of call graphs produced by SVF.

**Comment by rainoftime** [comment]
The issue has been fixed.
